application: petele-home-automation
version: 20140723-1
runtime: python27
threadsafe: yes
api_version: 1


handlers:
- url: /images
  static_dir: images
  secure: always

- url: /scripts
  static_dir: scripts
  secure: always

- url: /fonts
  static_dir: fonts
  secure: always

- url: /styles
  static_dir: styles
  secure: always

- url: /
  static_files: index.html
  upload: index.html
  expiration: "0s"
  login: admin

- url: /.*
  static_files: 404.html
  upload: 404.html
  application_readable: true
  expiration: "60m"

