application: petele-home-automation
version: 20150213-1
runtime: python27
threadsafe: yes
api_version: 1


handlers:
- url: /scripts
  static_dir: scripts
  secure: always
  login: admin

- url: /styles
  static_dir: styles
  secure: always
  login: admin

- url: /images
  static_dir: images
  secure: always

- url: /bower_components
  static_dir: bower_components
  secure: always
  login: admin

- url: /elements
  static_dir: elements
  secure: always
  login: admin

- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico

- url: /sw-offline.js
  static_files: sw-offline.js
  upload: sw-offline.js
  expiration: "0s"
  secure: always

- url: /offline.html
  static_files: 404.html
  upload: 404.html
  expiration: "0s"
  secure: always

- url: /manifest.json
  static_files: manifest.json
  upload: manifest.json
  expiration: "0s"
  secure: always

- url: /logs
  static_files: log.html
  upload: log.html
  expiration: "0s"
  secure: always
  login: admin

- url: /switch
  static_files: switch.html
  upload: switch.html
  expiration: "0s"
  login: admin
  secure: always

- url: /.*
  static_files: index.html
  upload: index.html
  expiration: "0s"
  login: admin
  secure: always


